import { FormItemProps, FormProps } from "antd";

export const antdFormItemProps: Array<keyof FormItemProps> = [
	"colon",
	"dependencies",
	"extra",
	"getValueFromEvent",
	"getValueProps",
	"hasFeedback",
	"help",
	"hidden",
	"htmlFor",
	"initialValue",
	"label",
	"labelAlign",
	"labelCol",
	"messageVariables",
	"name",
	"normalize",
	"noStyle",
	"preserve",
	"required",
	"rules",
	"shouldUpdate",
	"tooltip",
	"trigger",
	"validateFirst",
	"validateStatus",
	"validateTrigger",
	"valuePropName",
	"wrapperCol",
	"fieldKey",
	"isListField",
];

export const antdFormProps: Array<keyof FormProps> = [
	"colon",
	"component",
	"fields",
	"form",
	"initialValues",
	"labelAlign",
	"labelCol",
	"layout",
	"name",
	"preserve",
	"requiredMark",
	"scrollToFirstError",
	"size",
	"validateMessages",
	"validateTrigger",
	"wrapperCol",
	"onFieldsChange",
	"onFinish",
	"onFinishFailed",
	"onValuesChange",
];
